Repository technojam/developer-roadmap, pull requests merged in 2024-10, with the labels that each got.

#44 Update README.md
  Web Development/README.md
Labels: wontfix

#50 Add Open Source Contributions Roadmap
  Open Source/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#52 issue #51: Django roadmap added
  Django Developer/README.md
Labels: hacktoberfest-accepted

#53 Add Blockchain Developer Roadmap
  Blockchain Developer/readme.md
Labels: hacktoberfest-accepted

#54 Web 3.0 Development Roadmap
  Web 3.0 Development/readme.md
Labels: hacktoberfest-accepted

#55 Beginner friendly roadmap to Devops
  Devops/readme.md
Labels: hacktoberfest-accepted
